### ISSUE TITLE
Orthography error on the description of the project.

### ISSUE THREAD

**Issue by tiagopaes** [asouza/setupmyproject#7]
Exists an orthographic error on the description of the project that I can not fix. The word 'minutes' is written in the Portuguese language.

**Comment by marabesi** [comment]
up

"in less than five minutos"

<img width="820" alt="screen shot 2017-03-14 at 21 44 35" src="https://cloud.githubusercontent.com/assets/2129872/23928613/7aa5376c-08ff-11e7-9327-d9c406a40493.png">

**Comment by marabesi** [comment]
ping @asouza

**Comment by fwfurtado** [comment]
Hi @marabesi!

This is already fixed.
[]s
